<a href="https://colab.research.google.com/github/pavanbaki/Machine_Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
# Is for mathematical operations

import numpy as np

a = [1,2,3,4]

arr1 = np.array(a)

b=[[1,2,3,4],[5,6,7,8]]

arr2 = np.array(b)

print(arr1)
print(arr2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(type(a),
      type(arr1),
      type(b),
      type(arr2))

<class 'list'> <class 'numpy.ndarray'> <class 'list'> <class 'numpy.ndarray'>


In [ ]:
import sys

s= range(1000)

print("Size of each element in the list in bytes",sys.getsizeof(s))

print("complete list size in bytes",sys.getsizeof(s) * len(s))

Size of each element in the list in bytes 48
complete list size in bytes 48000


In [ ]:
# we are checking comparission between numpy size and normal size of "sys" packages

import numpy as np

s = np.arange(1000)

print("Size of each element in the list in bytes",s.itemsize)

print("Complete size in bytes ",s.size *s.itemsize)

Size of each element in the list in bytes 8
Complete size in bytes  8000


In [ ]:
# import time library and make excution time taking by the system

import time

a=range(1000) #[0-999]

b=range(1000) #[0-999]

start = time.time()
ab = [(a * b) for a , b in zip(a,b)] # list compression

# creating a concised form of complete list and for loop or any other conditions statements

end = time.time()

print("Total time taken",end-start)

Total time taken 0.00035262107849121094


In [ ]:
import numpy
import time

arr1 = np.arange(1000)
arr2 = np.arange(1000)

start = time.time()

arr_mul = arr1 * arr2

end =time.time()
print("Total time taken ",end-start)


Total time taken  7.963180541992188e-05


In [ ]:
lst = [1,2,3]
arr= np.array(lst)

print(arr)

[1 2 3]


In [ ]:
print(last + 1 )

NameError: ignored

In [ ]:
print(arr +1)

[2 3 4]


In [ ]:
arr1 =np.array([[1,2,3,4],[5,6,7,8]],ndmin = 2)
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np

arr1 = np.array([1,2,3])

print(arr1)

[1 2 3]


In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr2 = np.zeros([2,2])

print(arr2)

[[0. 0.]
 [0. 0.]]


In [ ]:
lst1 = [1,2,3,4.52,True,False,2+3j,"Codegnan"]

print(lst1)

[1, 2, 3, 4.52, True, False, (2+3j), 'Codegnan']


In [ ]:
type(lst1)

list

In [ ]:
# 4 differenct type of data structures in python 

# list - []
#Typle -()
#Dictionary - {Key - Value}
#Set - {Numerical values and unique variables}

In [ ]:
# Create an n-dimessional array

a = [[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
import numpy as np

np.array(a,ndmin=10)

array([[[[[[[[[[1, 2, 3],
               [4, 5, 6]]]]]]]]]])

In [14]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
arr[2,0]

7

In [16]:
arr[3,0]

IndexError: ignored

In [18]:
np.arange(2,2,0)

ZeroDivisionError: ignored

In [19]:
#Numpy - Is for mathematical operations. Like creating and manipulating arrays and numbers

# Pandas - Is the data handling mechanism and tool. Which can handle the datasets to process into models

In [21]:
np.random.rand(3,2)

array([[0.91661907, 0.69987021],
       [0.39459303, 0.6331838 ],
       [0.56170162, 0.86709798]])

In [23]:
arr1 = np.random.rand(3,2)

arr2 = np.random.rand(3,2)

sum1 = np.add(arr1,arr2)

print(arr1)
print(arr2)
print(sum1)

[[0.42279156 0.95771089]
 [0.58431853 0.35047784]
 [0.44909211 0.5709748 ]]
[[0.85751517 0.51615709]
 [0.7898181  0.37566809]
 [0.25537759 0.23266874]]
[[1.28030672 1.47386797]
 [1.37413663 0.72614592]
 [0.7044697  0.80364354]]


In [25]:
sub1 = np.subtract(arr1,arr2)

print(sub1)

[[-0.43472361  0.4415538 ]
 [-0.20549957 -0.02519025]
 [ 0.19371452  0.33830605]]


In [29]:
# indexing and slicing

a = [1,2,3,7,20.5,"codegnan",True]

a[5]

'codegnan'

In [30]:
#slicing  = [start : end+1]

a[0:6]


[1, 2, 3, 7, 20.5, 'codegnan']

In [31]:
a[-1]

True

In [32]:
a[-3]

20.5

In [33]:
a[:5]

[1, 2, 3, 7, 20.5]

In [34]:
a[:-1]

[1, 2, 3, 7, 20.5, 'codegnan']

In [35]:
a[-6:-1]

[2, 3, 7, 20.5, 'codegnan']

In [36]:
a = [1,2,3,7,20.5,"codegnan",True,1,2,3,7,20.5,"codegnan",True,1,2,3,7,20.5,"codegnan",True,1,2,3,7,20.5,"codegnan",True,]

a[0:10:2]

[1, 3, 20.5, True, 2]

In [41]:
a.reverse()

In [42]:
a

[True,
 'codegnan',
 20.5,
 7,
 3,
 2,
 1,
 True,
 'codegnan',
 20.5,
 7,
 3,
 2,
 1,
 True,
 'codegnan',
 20.5,
 7,
 3,
 2,
 1,
 True,
 'codegnan',
 20.5,
 7,
 3,
 2,
 1]

In [43]:
#The skip value will take start and end+1 variables and we are skipping values in between
a = [1,2,5,7,20.5,"Codegnan", True,1,2,5,7,20.5,"Codegnan", True,1,2,5,7,20.5,"Codegnan", True]

a[0:10:3]

[1, 7, True, 5]