<a href="https://colab.research.google.com/github/pavanbaki/Machine_Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
# Is for mathematical operations

import numpy as np

a = [1,2,3,4]

arr1 = np.array(a)

b=[[1,2,3,4],[5,6,7,8]]

arr2 = np.array(b)

print(arr1)
print(arr2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [2]:
print(type(a),
      type(arr1),
      type(b),
      type(arr2))

<class 'list'> <class 'numpy.ndarray'> <class 'list'> <class 'numpy.ndarray'>


In [3]:
import sys

s= range(1000)

print("Size of each element in the list in bytes",sys.getsizeof(s))

print("complete list size in bytes",sys.getsizeof(s) * len(s))

Size of each element in the list in bytes 48
complete list size in bytes 48000


In [4]:
# we are checking comparission between numpy size and normal size of "sys" packages

import numpy as np

s = np.arange(1000)

print("Size of each element in the list in bytes",s.itemsize)

print("Complete size in bytes ",s.size *s.itemsize)

Size of each element in the list in bytes 8
Complete size in bytes  8000


In [9]:
# import time library and make excution time taking by the system

import time

a=range(1000) #[0-999]

b=range(1000) #[0-999]

start = time.time()
ab = [(a * b) for a , b in zip(a,b)] # list compression

# creating a concised form of complete list and for loop or any other conditions statements

end = time.time()

print("Total time taken",end-start)

Total time taken 0.00035262107849121094


In [10]:
import numpy
import time

arr1 = np.arange(1000)
arr2 = np.arange(1000)

start = time.time()

arr_mul = arr1 * arr2

end =time.time()
print("Total time taken ",end-start)


Total time taken  7.963180541992188e-05


In [11]:
lst = [1,2,3]
arr= np.array(lst)

print(arr)

[1 2 3]


In [12]:
print(last + 1 )

NameError: ignored

In [13]:
print(arr +1)

[2 3 4]


In [14]:
arr1 =np.array([[1,2,3,4],[5,6,7,8]],ndmin = 2)
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]
