<a href="https://colab.research.google.com/github/pavanbaki/Machine_Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
# Is for mathematical operations

import numpy as np

a = [1,2,3,4]

arr1 = np.array(a)

b=[[1,2,3,4],[5,6,7,8]]

arr2 = np.array(b)

print(arr1)
print(arr2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(type(a),
      type(arr1),
      type(b),
      type(arr2))

<class 'list'> <class 'numpy.ndarray'> <class 'list'> <class 'numpy.ndarray'>


In [ ]:
import sys

s= range(1000)

print("Size of each element in the list in bytes",sys.getsizeof(s))

print("complete list size in bytes",sys.getsizeof(s) * len(s))

Size of each element in the list in bytes 48
complete list size in bytes 48000


In [ ]:
# we are checking comparission between numpy size and normal size of "sys" packages

import numpy as np

s = np.arange(1000)

print("Size of each element in the list in bytes",s.itemsize)

print("Complete size in bytes ",s.size *s.itemsize)

Size of each element in the list in bytes 8
Complete size in bytes  8000


In [ ]:
# import time library and make excution time taking by the system

import time

a=range(1000) #[0-999]

b=range(1000) #[0-999]

start = time.time()
ab = [(a * b) for a , b in zip(a,b)] # list compression

# creating a concised form of complete list and for loop or any other conditions statements

end = time.time()

print("Total time taken",end-start)

Total time taken 0.00035262107849121094


In [ ]:
import numpy
import time

arr1 = np.arange(1000)
arr2 = np.arange(1000)

start = time.time()

arr_mul = arr1 * arr2

end =time.time()
print("Total time taken ",end-start)


Total time taken  7.963180541992188e-05


In [ ]:
lst = [1,2,3]
arr= np.array(lst)

print(arr)

[1 2 3]


In [ ]:
print(last + 1 )

NameError: ignored

In [ ]:
print(arr +1)

[2 3 4]


In [ ]:
arr1 =np.array([[1,2,3,4],[5,6,7,8]],ndmin = 2)
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
import numpy as np

arr1 = np.array([1,2,3])

print(arr1)

[1 2 3]


In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2 = np.zeros([2,2])

print(arr2)

[[0. 0.]
 [0. 0.]]


In [8]:
lst1 = [1,2,3,4.52,True,False,2+3j,"Codegnan"]

print(lst1)

[1, 2, 3, 4.52, True, False, (2+3j), 'Codegnan']


In [9]:
type(lst1)

list

In [11]:
# 4 differenct type of data structures in python 

# list - []
#Typle -()
#Dictionary - {Key - Value}
#Set - {Numerical values and unique variables}

In [12]:
# Create an n-dimessional array

a = [[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [13]:
import numpy as np

np.array(a,ndmin=10)

array([[[[[[[[[[1, 2, 3],
               [4, 5, 6]]]]]]]]]])